; Generated by MethASM
; x86-64 Assembly Output

bits 64

section .text
; Code section

; First pass: processing 1 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 21)

section .text

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 176    ; Allocate 176 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_0:
    mov rax, 1
    ; Store to variable: a
    mov dword [rbp - 4], eax  ; To stack [rbp - 4]
    mov rax, 2
    ; Store to variable: b
    mov dword [rbp - 8], eax  ; To stack [rbp - 8]
    ; Load variable: a
    movsxd rax, dword [rbp - 4]  ; From stack [rbp - 4]
    push rax
    mov rax, 0
    mov r10, rax
    pop rax
    cmp rax, r10
    setne al
    movzx rax, al
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    test rax, rax
    jz ir_sc_false_5
ir_sc_rhs_3:
    ; Load variable: b
    movsxd rax, dword [rbp - 8]  ; From stack [rbp - 8]
    push rax
    mov rax, 0
    mov r10, rax
    pop rax
    cmp rax, r10
    setne al
    movzx rax, al
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    test rax, rax
    jz ir_sc_false_5
ir_sc_true_4:
    mov rax, 1
    mov [rbp - 32], rax
    jmp ir_sc_end_6
ir_sc_false_5:
    mov rax, 0
    mov [rbp - 32], rax
ir_sc_end_6:
    mov rax, [rbp - 32]
    test rax, rax
    jz ir_if_next_2
    mov rax, 0
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    test rax, rax
    jz ir_errdefer_ok_7
    jmp ir_errdefer_end_8
ir_errdefer_ok_7:
ir_errdefer_end_8:
    mov rax, 0
    jmp Lmain_exit
    jmp ir_if_end_1
ir_if_next_2:
ir_if_end_1:
    mov rax, 1
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    test rax, rax
    jz ir_errdefer_ok_9
    jmp ir_errdefer_end_10
ir_errdefer_ok_9:
ir_errdefer_end_10:
    mov rax, 1
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    mov [rsp + 32], rax ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    mov rcx, [rsp + 32] ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
